# Generated by Django 3.0.3 on 2020-03-04 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('telephone', models.BigIntegerField(null=True)),
                ('birthday', models.DateField(default='1999-05-10')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDescuento', models.CharField(max_length=20)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('day', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='NominaDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=20)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instrumentos', models.CharField(choices=[('TARJETA', 'tarjeta'), ('EFECTIVO', 'efectivo')], max_length=9)),
                ('Monto', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noTarjeta', models.BigIntegerField()),
                ('CVV', models.IntegerField()),
                ('cedula', models.IntegerField()),
                ('vencimiento', models.DateField()),
                ('banco', models.CharField(choices=[('PROVINCIAL', 'Provincial'), ('BANPLUS', 'Banplus'), ('MERCANTIL', 'Mercantil')], max_length=12)),
                ('idPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Recibo')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('serializador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Prod_Lista')),
            ],
        ),
        migrations.CreateModel(
            name='NominaDetallada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NominaDept')),
            ],
        ),
        migrations.CreateModel(
            name='ListaDescuentoP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('porcentaje', models.IntegerField()),
                ('serial', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Prod_Lista')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDetallada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioI', models.IntegerField()),
                ('precioF', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Factura')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Prod_Lista')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NominaDetallada'),
        ),
        migrations.AddField(
            model_name='factura',
            name='serialDescuento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Descuento'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NominaDetallada')),
            ],
        ),
    ]
