# Generated by Django 3.0.3 on 2020-02-13 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('telephone', models.BigIntegerField(default='', editable=False)),
                ('birthday', models.DateField(default='1999-05-10')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDescuento', models.CharField(max_length=20)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('day', models.DateField(default='1965-05-02')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='NominaDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('serializador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Prod_Lista')),
            ],
        ),
        migrations.AddField(
            model_name='prod_lista',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ProductoId'),
        ),
        migrations.CreateModel(
            name='NominaDetallada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NominaDept')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDetallada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NominaDetallada'),
        ),
        migrations.AddField(
            model_name='factura',
            name='serialDescuento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Descuento'),
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NominaDetallada')),
            ],
        ),
    ]
