# Generated by Django 3.0.2 on 2020-01-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmen_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=10)),
                ('hours', models.IntegerField(default=8)),
                ('salary', models.IntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
                ('department_name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='polls.Department')),
            ],
        ),
    ]
