# Generated by Django 3.0.2 on 2020-02-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200127_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDescuento', models.CharField(max_length=20)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacturaDetallada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Factura')),
            ],
        ),
        migrations.CreateModel(
            name='NominaDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NominaDetallada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NominaDept')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.IntegerField()),
                ('sold', models.IntegerField()),
                ('serializador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Prod_Lista')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department_name',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='identification',
            new_name='cedula',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telephone',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='prod_lista',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ProductoId'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NominaDetallada'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.NominaDetallada'),
        ),
    ]
