# Generated by Django 3.0.2 on 2020-02-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200210_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telephone',
            field=models.BigIntegerField(),
        ),
    ]
