# Generated by Django 3.0.2 on 2020-02-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200210_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='birthday',
            field=models.DateField(default='1999-05-10'),
        ),
        migrations.AddField(
            model_name='factura',
            name='day',
            field=models.DateField(default='1965-05-02'),
        ),
        migrations.AddField(
            model_name='factura',
            name='serialDescuento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Descuento'),
        ),
        migrations.AddField(
            model_name='prod_lista',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
